# Generated by Django 4.2.25 on 2025-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='ubicacion',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
