# Generated by Django 4.2.25 on 2025-10-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_obra_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='direccion',
        ),
    ]
