# Generated by Django 4.2.25 on 2025-10-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_candidato_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertalaboral',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=50),
        ),
    ]
