# Generated by Django 4.2.25 on 2025-11-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_obra_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertalaboral',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
